== Mengelola Paket Menggunakan npm dan yarn

=== Apakah npm Itu?

Node.js memungkinkan developer untuk mengembangkan aplikasi secara
modular dengan memisahkan berbagai komponen _reusable code_ ke dalam
pustaka (_library_). Berbagai pustaka tersebut bisa diperoleh di
http://www.npmjs.com[]. Node.js menyediakan perintah _npm_ untuk mengelola paket pustaka di repositori tersebut. Untuk menggunakan utilitas ini,pemrogram harus terkoneksi dengan Internet.

=== Menggunakan npm

Saat melakukan instalasi Node.js, secara otomatis _npm_ akan
disertakan. Dengan perintah _npm_ tersebut, seorang pemrogram bisa
mengelola pustaka yang tersedia di repositori. Jika pemrogram mempunya
pustakan yang bisa digunakan oleh orang lain, maka pemrogram yang
bersangkutan juga bisa menyimpan pustaka tersebut ke dalam repositori
sehingga memungkinkan untuk diinstall oleh pemrogram-pemrogram lain di
seluruh dunia. Sintaksis lengkap dari penggunaan perintah _npm_ ini
adalah sebagai berikut:

----
Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link, 
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /home/bpdp/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@4.0.5 /opt/software/nodejs-dev-tools/node-v7.4.0-linux-x64/lib/node_modules/npm
----

[NOTE]
====
Lokasi direktori pada sintaks penggunaan _npm_ tersebut adalah lokasi
spesifik di komputer penulis (misalnya: */home/bpdp/.npmrc*).
====

Pada bagian berikut, kita akan membahas lebih lanjut penggunaan perintah _npm_ tersebut.

==== Instalasi Paket

_npm_ sebenarnya bukan merupakan singkatan dari _Node Package Manager_,
meskipun seringkali orang menterjemahkan dengan singkatan tersebut.
_npm_ seharusnya ditulis dalam huruf kecil semua seperti yang
dijelaskan pada https://docs.npmjs.com/misc/faq[FAQ]. _npm_ merupakan
perintah di _shell / command line_. Struktur perintahnya adalah: _npm
perintah argumen_. Instalasi paket dilakukan dengan perintah berikut: 

----
$ npm install namapaket
----

Perintah diatas akan memasang versi terakhir dari paket _namapaket_.

==== Struktur Instalasi Paket Node.js

Dalam installasi paket pustaka, berkas-berkas akan terletak dalam folder lokal aplikasi _node_modules_. Pada mode installasi paket pustaka global (dengan -g atau –global dibelakang baris perintah), paket pustaka akan dipasang pada _/usr/lib/node_modules_ (dengan lokasi installasi Node.js standar). Mode global memungkinkan paket pustaka digunakan tanpa memasang paket pustaka pada setiap folder lokal aplikasi. Mode global ini juga membutuhkan hak administrasi lebih (sudo atau root) dari pengguna agar dapat menulis pada lokasi standar.

Jika berada pada direktori $HOME, maka paket-paket npm tersebut akan terinstall di $HOME/.npm, sedangkan jika kita berada di luar direktori $HOME, maka paket-paket tersebut akan terinstall di $CWD/node_modules ($CWD = _Current Working Directory_ - direktori aktif saat ini). Daftar paket pustaka yang terpasang dapat dilihat menggunakan perintah berikut:

----
$ npm ls
----

Selain melihat daftar paket pustaka yang digunakan dalam aplikasi maupun global, perintah diatas juga akan menampilkan paket dependensi dalam struktur pohon. Jika kita belum menginstall paket-paket yang diperlukan, akan muncul peringatan. 

----
$ npm ls --depth=0
weberiajs@1.0.0 /home/bpdp/kerjaan/git-repos/weberia/weberiajs
├── UNMET DEPENDENCY hapi@^11.0.2
└── jsonld@0.4.2

npm ERR! missing: hapi@^11.0.2, required by weberiajs@1.0.0
----

Jika sudah terinstall, perintah "npm ls" akan menampilkan struktur
dari paket yang telah terinstall dalam bentuk struktur pohon.

==== Menghapus Paket / _Uninstall_

Menghapus paket pustaka menggunakan npm pada dasarnya hampir sama
dengan saat memasang paket, namun dengan perintah _uninstall_. Berikut
perintah lengkapnya:

----
$ npm uninstall namapaket
----

==== Mencari Paket

Untuk mencari paket, gunakan argumen _search_ dan nama atau bagian dari nama paket yang dicari. Contoh berikut ini akan mencari paket dengan kata kunci ’sha512’:

----
$ npm search sha512
----

Setelah menemukan paketnya, pemrogram bisa menginstall langsung ataupun melihat informasi lebih lanjut tentang pustakan tersebut.

==== Menampilkan Informasi Paket

Setelah mengetahui nama paket, pemrogram bisa memperoleh informasi
lebih lanjut dalam format JSON menggunakan parameter _view_. Contoh
dibawah ini menampilkan rincian dalam format JSON dari paket _arangojs_: 

----
$ npm info arangojs
----

==== Memperbaharui Paket

Jika terdapat versi baru, kita bisa memperbaharui secara otomatis menggunakan argumen _update_ berikut ini:

----
$ npm update
----
