== REPL dan Dasar-dasar JavaScript di Node.js

=== REPL

REPL adalah lingkungan pemrograman interaktif, tempat developer bisa mengetikkan program per baris dan langsung mengeksekusi hasilnya. Biasanya ini digunakan untuk menguji perintah-perintah yang cukup dijalankan pada satu baris atau satu blok segmen kode sumber saja. Karena fungsinya itu, maka istilah yang digunakan adalah REPL (read-eval-print-loop), yaitu loop atau perulangan baca perintah - evaluasi perintah - tampilkan hasil. REPL sering juga disebut sebagai _interactive top level_ atau _language shell_. "Tradisi" ini sudah dimulai sejak jaman LISP di mesin UNIX di era awal pengembangan _development tools_. Saat ini hampir semua _interpreter/compiler_ mempunyai REPL, misalnya Python, Ruby, Scala, PHP, berbagai interpreter/compiler LISP, dan tidak ketinggalan Node.js.

==== Mengaktifkan REPL

Untuk mengaktifkan REPL dari Node.js, _executable command line program_-nya adalah *node* (atau *nodejs* pada beberapa sistem operasi, misalnya Ubuntu Linux). Jika *node* dipanggil dengan argumen nama file JavaScript, maka file JavaScript tersebut akan dieksekusi, sementara jika tanpa argumen, akan masuk ke REPL:

----
$ node
>
----

Tanda *>* adalah tanda bahwa REPL Node.js siap untuk menerima perintah. Untuk melihat perintah-perintah REPL, bisa digunakan *.help*.

----
> .help
.break    Sometimes you get stuck, this gets you out
.clear    Alias for .break
.editor   Enter editor mode
.exit     Exit the repl
.help     Print this help message
.load     Load JS from a file into the REPL session
.save     Save all evaluated commands in this REPL session to a file
> 
----

Untuk keluar dari mode REPL, tekan *Ctrl-D* sekali atau *Ctrl-C* dua
kali.

----
$ node
> 
(^C again to quit)
> 
----

==== Perintah-perintah REPL

Pada sesi REPL, kita bisa memberikan perintah internal REPL maupun perintah-perintah lain yang sesuai dan dikenali sebagai perintah JavaScript. Perintah internal REPL Node.js terdiri atas:

* *.break*: keluar dan melepaskan diri dari "keruwetan" baris perintah di REPL.
* *.clear*: alias untuk .break
* *.editor*: memasuki mode editor - memungkinkan mengedit lebih dari
  satu baris
* *.exit*: keluar dari sesi REPL (bisa juga dengan menggunakan Ctrl-D)
* *.help*: menampilkan pertolong perintah internal REPL
* *.load*: membaca dan mengeksekusi perintah-perintah JavaScript yang terdapat pada suatu file.
* *.save*: menyimpan sesi REPL ke dalam suatu file.

Contoh untuk *.load*:

[source,javascript]
----
$ node
> .load /home/bpdp/kerjaan/src/javascript/nodejs/hello.js
> var http = require('http');
undefined
> http.createServer(function (req, res) {
...   res.writeHead(200, {'Content-Type': 'text/plain'});
...   res.end('Hello World\n');
... }).listen(1337, '127.0.0.1');
{ domain: null,
  _events: 
   { request: [Function],
     connection: [Function: connectionListener],
     clientError: [Function] },
  _maxListeners: 10,
  _connections: 0,
  connections: [Getter/Setter],
  _handle: null,
  _usingSlaves: false,
  _slaves: [],
  allowHalfOpen: true,
  httpAllowHalfOpen: false,
  timeout: 120000 }
> console.log('Server running at http://127.0.0.1:1337/');
Server running at http://127.0.0.1:1337/
undefined
> 
----

Setelah keluar dari sesi REPL, maka port akan ditutup dan hasil eksekusi di atas akan dibatalkan. Untuk menyimpan hasil sesi REPL menggunakan *.save*, jika tanpa menyebutkan direktori, maka akan disimpan di direktori aktif saat itu. Contoh:

[source, javascript]
----
$ node
> console.log("Selamat datang di Node.js")
Selamat datang di Node.js
undefined
> .save /home/bpdp/kerjaan/src/javascript/nodejs/welcome.js
Session saved to:/home/bpdp/kerjaan/src/javascript/nodejs/welcome.js
> exit
$ cat /home/bpdp/kerjaan/src/javascript/nodejs/welcome.js 
console.log("Selamat datang di Node.js")
$
----

=== Dasar-dasar JavaScript di Node.js

Node.js merupakan sistem peranti lunak yang merupakan implementasi dari bahasa pemrograman JavaScript. Spesifikasi JavaScript yang diimplementasikan merupakan spesifikasi resmi dari ECMAScript serta CommonJS (http://commonjs.org). Dengan demikian, jika anda sudah pernah mempelajari JavaScript sebelumnya, tata bahasa dari perintah yang dipahami oleh Node.js masih tetap sama dengan JavaScript.

==== Membaca Masukan dari _Stream_ / Masukan Standar (stdin)

Untuk lebih memahami dasar-dasar JavaScript serta penerapannya di Node.js, seringkali kita perlu melakukan simulasi pertanyaan - proses - keluaran jawaban. Proses akan kita pelajari seiring dengan materi-materi berikutnya, sementara untuk keluaran, kita bisa menggunakan *console.log*. Bagian ini akan menjelaskan sedikit tentang masukan.

Perintah untuk memberi masukan di Node.js sudah tersedia pada pustaka
API http://www.nodejs.org/api/readline.html[Readline]. Pola dari masukan ini adalah sebagai berikut:

* me-_require_ pustaka Readline
* membuat _interface_ untuk masukan dan keluaran
* .. gunakan interface ..
* .. gunakan interface ..
* .. gunakan interface ..
* .. gunakan interface ..
* ..
* ..
* tutup _interface_

Implementasi dari pola diatas bisa dilihat pada kode sumber berikut ini (diambil dari manual Node.js):

[source,javascript]
.readline.js
----
include::kode/bab-02/readline.js[]
----

[NOTE]
====
_function(answer)_ pada listing di atas merupakan _anonymous function_ atau fungsi anonimus (sering juga disebut _lambda function_ / fungsi lambda. Posisi fungsi pada listing tersebut disebut dengan fungsi _callback_. Untuk keperluan pembahasan saat ini, untuk sementara yang perlu dipahami adalah hasil input akan dimasukkan ke _answer_ untuk diproses lebih lanjut. Fungsi dan _callback_ akan dibahas lebih lanjut pada pembahasan berikutnya.
====

==== Nilai/Value dan Tipe Data

Program dalam JavaScript akan berhubungan dengan data atau nilai. Setiap nilai mempunyai tipe tertentu. JavaScript mengenali berbagai tipe berikut ini:

* Angka: bulat (misalnya 4) atau pecahan (misalnya 3.75)
* _Boolean_: nilai benar (true) dan salah (false)
* String: diapit oleh tanda petik ganda ("contoh string") atau tunggal (’contoh string’)
* _null_
* _undefined_

JavaScript adalah bahasa pemrograman yang mengijinkan pemrogram untuk tidak mendefinisikan tipe data pada saat deklarasi, atau sering juga disebut sebagai _dynamically typed language_:

[source,javascript]
.dynamic.js
----
include::kode/bab-02/dynamic.js[]
----

Pada contoh di atas, kita bisa melihat bahwa data akan dikonversi secara otomatis pada saat program dieksekusi.

[NOTE]
====
Khusus untuk operator ``+'', JavaScript akan melakukan penggabungan string (_string concatenation_), tetapi untuk operator lain, akan dilakukan operasi matematis sesuai operator tersebut (-,/,*). Konversi string ke tipe numerik bisa dilakukan dengan _parseInt(string)_ (jika bilangan bulat) dan _parseFloat(string)_ (jika
bilangan pecahan).
====

==== Variabel

Variabel adalah suatu nama yang didefinisikan untuk menampung suatu nilai. Nama ini akan digunakan sebagai referensi yang akan menunjukkan ke nilai yang ditampungnya. Nama variabel disebut dengan _identifier_ / pengenal. Ada beberapa syarat pemberian nama _identifier_ di JavaScript:

* Dimulai dengan huruf, _underscore_ (_), atau tanda dollar ($).
* Karakter berikutnya bisa berupa angka, selain ketentuan pertama di atas.
* Membedakan huruf besar - kecil.

Konvensi yang digunakan oleh pemrogram JavaScript terkait dengan penamaan ini adalah variasi dari metode _camel case_, yaitu __camelBack_. Contoh: jumlahMahasiswa, linkMenu, status.

==== Konstanta

Konstanta mirip dengan variabel, hanya saja sifatnya _read-only_, tidak bisa diubah-ubah setelah ditetapkan. Untuk menetapkan konstanta di JavaScript, digunakan kata kunci _const_. Contoh:

[source,javascript]
.const.js
----
include::kode/bab-02/const.js[]
----

Konvensi penamaan konstanta adalah menggunakan huruf besar semua. Bagian ini (sampai saat buku ini ditulis) hanya berlaku di Firefox dan Google Chrome - V8 (artinya berlaku juga untuk Node.js).

==== Fungsi

===== Pengertian Fungsi

Fungsi merupakan subprogram atau suatu bagian dari keseluruhan program
yang ditujukan untuk mengerjakan suatu pekerjaan tertentu dan
(biasanya) menghasilkan suatu nilai kembalian. Subprogram ini relatif
independen terhadap bagian-bagian lain sehingga memenuhi kaidah
"bisa-digunakan-kembali" atau _reusable_ pada beberapa program yang
memerlukan fungsionalitasnya. Fungsi dalam ilmu komputer sering kali
juga disebut dengan _procedure, routine_, atau _method_.

===== Definisi Fungsi

Definisi fungsi dari JavaScript di Node.js bisa dilakukan dengan sintaksis berikut ini:

[source,javascript]
----
function namaFungsi(argumen1, argumen2, ... , argumentN) {
  ..
  JavaScript code ..
  JavaScript code ..
  JavaScript code ..
  JavaScript code ..
  ..
}
----

Setelah dideklarasikan, fungsi tersebut bisa dipanggil dengan cara sebagai berikut:

[source, javascript]
----
..
..
  namaFungsi(argumen1, argumen2, ..., argumenN);
..
..
----

Contoh dalam program serta pemanggilannya adalah sebagai berikut:

[source, javascript]
----
$ node
> function addX(angka) {
... console.log(angka + 10);
... }
undefined
> addX(20);
30
undefined
>
> function add2Numbers(angka1, angka2) {
... return angka1 + angka2;
... }
undefined
> console.log("232 + 432 = " + add2Numbers(232, 432));
232 + 432 = 664
undefined
>
----

===== Fungsi Anonim

Fungsi anonim adalah fungsi tanpa nama, pemrogram tidak perlu memberikan nama ke fungsi. Biasanya fungsi anonimus ini hanya digunakan untuk fungsi yang dikerjakan pada suatu bagian program saja dan tidak dengan maksud untuk dijadikan komponen yang bisa dipakai di bagian lain dari program (biasanya untuk menangani _event_ atau _callback_). Untuk mendeklarasikan fungsi ini, digunakan literal _function_.

[source, javascript]
.fungsiAnonim.js
----
include::kode/bab-02/fungsiAnonim.js[]
----

===== Fungsi Rekursif

Fungsi rekursif adalah fungsi yang memanggil dirinya sendiri. Contoh dari aplikasi fungsi rekursif adalah pada penghitungan faktorial berikut:

[source, javascript]
.fungsiRekursif.js
----
include::kode/bab-02/fungsiRekursif.js[]
----

===== Fungsi di dalam Fungsi / _Nested Functions_

Saat mendefinisikan fungsi, di dalam fungsi tersebut pemrogram bisa mendefinisikan fungsi lainnya. Meskipun demikian, fungsi yang terletak alam suatu definisi fungsi tidak bisa diakses dari luar fungsi tersebut dan hanya tersedia untuk fungsi yang didefinisikan.

[source, javascript]
.nested.js
----
include::kode/bab-02/nested.js[]
----

==== Literal

Literal digunakan untuk merepresentasikan nilai dalam JavaScript. Ada beberapa tipe literal.

===== Literal Array

Array atau variabel berindeks adalah penampung untuk obyek yang menyerupai _list_ atau daftar. Obyek array juga menyediakan berbagai fungsi dan metode untuk mengolah anggota yang terdapat dalam daftar tersebut (terutama untuk operasi _traversal_ dan permutasi. Listing berikut menunjukkan beberapa operasi untuk literal array.

[source, javascript]
.array.js
----
include::kode/bab-02/array.js[]
----

===== Literal Boolean

Literal boolean menunjukkan nilai benar (true) atau salah (false).

[source, javascript]
.boolean.js
----
include::kode/bab-02/boolean.js[]
----

===== Literal Integer

Literal integer digunakan untuk mengekspresikan nilai bilangan bulat. Nilai bulangan bulat dalam JavaScript bisa dalam bentuk:

* _binary_ (basis 2): digit diawali dengan 0b.
* _decimal_ (basis 10): digit tanpa awalan nol.
* _octal_ (basis 8): digit diawali dengan 1 angka nol. Pada ECMA-262,
  bilangan _octal_ ini sudah tidak digunakan lagi.
* _hexadecimal_ (basis 16): digit diawali dengan 0x.

[source, javascript]
.integers.js
----
include::kode/bab-02/integers.js[]
----

===== Literal Floating-point

Literal ini digunakan untuk mengekspresikan nilai bilangan pecahan, misalnya 0.4343 atau bisa juga menggunakan E/e (nilai eksponensial), misalnya -3.1E12.

[source, javascript]
.floatingPoint.js
----
include::kode/bab-02/floatingPoint.js[]
----

===== Literal Obyek

Literal ini akan dibahas di bab yang menjelaskan tentang paradigma pemrograman berorientasi obyek di JavaScript.

===== Literal String

Literal string mengekspresikan suatu nilai dalam bentuk sederetan
karakter dan berada dalam tanda petik (ganda/"""" maupun tunggal/''). Contoh:

* "Kembali ke halaman utama"
* ’Lisensi’
* "Hari ini, Jum’at, tanggal 21 November"
* "1234.543"
* "baris pertama \n baris kedua"

Contoh terakhir di atas menggunakan karakter khusus (
*\n*). Karakter khusus ini sering disebut dengan _escape character_. Beberapa karakter khusus lainnya adalah:

* `\b`: Backspace
* `\f`: Form feed
* `\n`: New line
* `\r`: Carriage return
* `\t`: Tab
* `\v`: Vertical tab
* `\'`: Apostrophe atau single quote
* `\"`: Double quote
* `\\`: Backslash (`\`).
* `\XXX`: Karakter dengan pengkodean Latin-1 dengan tiga digit octal
  antara 0 and 377. (misal, `\251` adalah simbol hak cipta).
* `\xXX`: seperti di atas, tetapi hexadecimal (2 digit).
* `\uXXXX`: Karakter _Unicode_ dengan 3 digit karakter hexadecimal.

==== Struktur Data dan Representasi JSON

JSON (_JavaScript Object Notation_) adalah subset dari JavaScript dan
merupakan struktur data native di JavaScript. Bentuk dari representasi
struktur data JSON adalah sebagai berikut (diambil dari
http://en.wikipedia.org/wiki/JSON dengan sedikit perubahan):

[source, javascript]
.json.js
----
include::kode/bab-02/json.js[]
----

Dari representasi di atas, kita bisa membaca:

* Nilai data _firstname_ adalah _John_
* Data _address_ terdiri atas sub data _streetAddress_, _city_,
  _state_, dan _postalCode_ yang masing-masing mempunyai nilai data sendiri-sendiri.
* dan seterusnya

==== Aliran Kendali

Alur program dikendalikan melalui pernyataan-pernyataan untuk aliran kendali. Ada beberapa pernyataan aliran kendali yang akan dibahas.

===== Pernyataan Kondisi _if .. else if .. else_

Pernyataan ini digunakan untuk mengerjakan atau tidak mengerjakan suatu bagian atau blok program berdasarkan hasil evaluasi kondisi tertentu.

[source, javascript]
.if.js
----
include::kode/bab-02/if.js[]
----

===== Pernyataan _switch_

Pernyataan ini digunakan untuk mengevaluasi suatu ekspresi dan membandingkan sama atau tidaknya dengan suatu label tertentu di dalam struktur pernyataan switch, serta mengeksekusi perintah-perintah sesuai dengan label yang cocok.

[source, javascript]
.switch.js
----
include::kode/bab-02/switch.js[]
----

===== _Looping_

Looping atau sering juga disebut ``kalang'' adalah konstruksi program yang digunakan untuk melakukan suatu blok perintah secara berulang-ulang.

*for*

[source, javascript]
.for.js
----
include::kode/bab-02/for.js[]
----

Pernyataan ``for'' juga bisa digunakan untuk mengakses data yang tersimpam dalam struktur data JavaScript (JSON).

[source, javascript]
.forIn.js
----
include::kode/bab-02/forIn.js[]
----

*do .. while*

Pernyataan ini digunakan untuk mengerjakan suatu blok program selama suatu kondisi bernilai benar dengan jumlah minimal pengerjaan sebanyak 1 kali.

[source, javascript]
.doWhile.js
----
include::kode/bab-02/doWhile.js[]
----

*while*

Seperti _do .. while_, pernyataan ini digunakan untuk mengerjakan suatu blok program secara berulang-ulang selama kondisi bernilai benar. Meskipun demikian, bisa saja blok program tersebut tidak pernah dikerjakan jika pada saat awal expresi dievaluasi sudah bernilai _false_.

[source, javascript]
.while.js
----
include::kode/bab-02/while.js[]
----

*label, break, dan continue*

Bagian ini digunakan dalam _looping_ dan _switch_.

* _label_ digunakan untuk memberi pengenal pada suatu lokasi program sehingga bisa direferensi oleh _break_ maupun _continue_ (jikaa dikehendaki).
* _break_ digunakan untuk menghentikan eksekusi dan meneruskan alur program ke pernyataan setelah _looping_ atau _switch_
* _continue_ digunakan untuk meneruskan eksekusi ke iterasi atau ke kondisi switch berikutnya.

[source, javascript]
.breakContinue.js
----
include::kode/bab-02/breakContinue.js[]
----

[source, javascript]
.breakWithLabel.js
----
include::kode/bab-02/breakWithLabel.js[]
----

===== Penanganan Error

JavaScript mendukung pernyataan _try .. catch .. finally_ serta
_throw_ untuk menangani error. Meskipun demikian, banyak hal yang
tidak sesuai dengan konstruksi ini karena sifat JavaScript yang
_asynchronous_. Untuk kasus asynchronous, pemrogram lebih disarankan menggunakan _function callback_. Jika diperlukan, kita bisa mendefinisikan sendiri error dengana menggunakan pernyataan _throw_.

[source, javascript]
.try.js
----
include::kode/bab-02/try.js[]
----

[source, javascript]
.throw.js
----
include::kode/bab-02/throw.js[]
----
