== Paradigma Pemrograman di JavaScript

=== Pemrograman Fungsional

Pemrograman fungsional, atau sering disebut _functional programming_,
selama ini lebih sering dibicarakan di level para akademisi. Meskipun
demikian, saat ini terdapat kecenderungan paradigma ini semakin banyak
digunakan di industri. Contoh nyata dari implementasi paradigma ini di
industri antara lain adalah http://www.scala-lang.org[Scala],
http://www.ocaml.org[Ocaml], http://www.haskell.org[Haskell],
http://fsharp.org[F#], dan lain-lain. Dalam konteks paradigma
pemrograman, peranti lunak yang dibangun menggunakan pendekatan
paradigma ini akan terdiri atas berbagai fungsi yang mirip dengan
fungsi matematis. Fungsi matematis tersebut di-evaluasi dengan
penekanan pada penghindaran _state_ serta _mutable data_. Bandingkan dengan paradigma pemrograman prosedural yang menekankan pada _immutable data_ dan definisi berbagai prosedur dan fungsi untuk mengubah _state_ serta data.

JavaScript bukan merupakan bahasa pemrograman fungsional yang murni,
tetapi ada banyak fitur dari pemrograman fungsional yang terdapat
dalam JavaScript. Dalam hal ini, JavaScript banyak dipengaruhi oleh
bahasa pemrograman http://www.schemers.org/[Scheme]. Bab ini akan membahas beberapa fitur pemrograman fungsional di JavaScript. Pembahasan ini didasari pembahasan di bab sebelumnya tentang Fungsi di JavaScript.

==== Ekspresi Lambda

Ekspresi lambda / _lambda expression_ merupakan hasil karya dari ALonzo Church sekitar tahun 1930-an. Aplikasi dari konsep ini di dalam pemrograman adalah penggunaan fungsi sebagai parameter untuk suatu fungsi. Dalam pemrograman, _lambda function_ sering juga disebut sebagai fungsi anonimus (fungsi yang dipanggil/dieksekusi tanpa ditautkan (_bound_) ke suatu _identifier_). Berikut adalah implementasi dari konsep ini di JavaSCript:

[source, javascript]
.lambda.js
----
include::kode/bab-03/lambda.js[]
----

==== Higher-order Function

_Higher-order function_ (sering disebut juga sebagai _functor_ adalah suatu fungsi yang setidak-tidaknya menggunakan satu atau lebih fungsi lain sebagai parameter dari fungsi, atau menghasilkan fungsi sebagai nilai kembalian.

[source, javascript]
.hof.js
----
include::kode/bab-03/hof.js[]
----

==== Closure

Suatu _closure_ merupakan definisi suatu fungsi bersama-sama dengan lingkungannya. Lingkungan tersebut terdiri atas fungsi internal serta berbagai variabel lokal yang masih tetap tersedia saat fungsi utama / closure tersebut selesai dieksekusi.

[source, javascript]
.closure.js
----
include::kode/bab-03/closure.js[]
----

==== Currying

_Currying_ memungkinkan pemrogram untuk membuat suatu fungsi dengan cara menggunakan fungsi yang sudah tersedia secara parsial, artinya tidak perlu menggunakan semua argumen dari fungsi yang sudah tersediaa tersebut.

[source, javascript]
.currying.js
----
include::kode/bab-03/currying.js[]
----

=== Pemrograman Berorientasi Obyek

==== Pengertian

Pemrograman Berorientasi Obyek (selanjutnya akan disingkat PBO) adalah suatu paradigma pemrograman yang memandang bahwa pemecahan masalah pemrograman akan dilakukan melalui definisi berbagai kelas kemudian membuat berbagai obyek berdasarkan kelas yng dibuat tersebut dan setelah itu mendefinisikan interaksi antar obyek tersebut dalam memecahkan masalah pemrograman. Obyek bisa saling berinteraksi karena setiap obyek mempunyai properti (sifat / karakteristik) dan _method_ untuk mengerjakan suatu pekerjaan tertentu. Jadi, bisa dikatakan bahwa paradigma ini menggunakan cara pandang yang manusiawi dalam penyelesaian masalah.

Dengan demikian, inti dari PBO sebenarnya terletak pada kemampuan untuk mengabstraksikan berbagai obyek ke dalam kelas (yang terdiri atas properti serta method). Paradigma PBO biasanya juga mencakup _inheritance_ atau pewarisan (sehingga terbentuk skema yang terdiri atas _superclass_ dan _subclass_). Ciri lainnya adalah _polymorphism_ dan _encapsulation_ / pengkapsulan.

JavaScript adalah bahasa pemrograman yang mendukung PBO dan merupakan implementasi dari ECMAScript. Implementasi PBO di JavaScript adalah _prototype-based programming_ yang merupakan salah satu subset dari PBO. Pada _prototype-based programming_, kelas / _class_ tidak ada. Pewarisan diimplementasikan melalui _prototype_.

==== Definisi Obyek

Definisi obyek dilakukan dengan menggunakan definisi _function_, sementara _this_ digunakan di dalam definisi untuk menunjukkan ke obyek tersebut. Sementara itu, Kelas.prototype.namaMethod digunakan untuk mendefinisikan method dengan nama method namaMethod pada kelas Kelas. Perhatikan contoh pada listing berikut.

[source, javascript]
.obyek.js
----
include::kode/bab-03/obyek.js[]
----

==== _Inheritance_ / Pewarisan

Pewarisan di JavaScript bisa dicapai menggunakan _prototype_. Listing program berikut memperlihatkan bagaimana pewarisan diimplementasikan di JavaScript.

[source, javascript]
.inheritance.js
----
include::kode/bab-03/inheritance.js[]
----
