== Real-time Web Menggunakan Socket.io

=== Apa itu Real-time Web?

Real-time Web menunjukkan suatu pola interaksi aplikasi Web yang memungkinkan kedua sisi saling mengirimkan data saat terjadi perubahan, jadi tidak seperti pola interaksi yang menghendaki pemakai untuk me-_refresh_ browser jika menginginkan data / informasi / _update_ terbaru dari sisi server. Contoh dari real-time Web adalah Facebook dan Twitter. Pemakai akan mendapatkan _update_ secara langsung saat terjadi perubahan (komentar baru, pesan masuk, permintaan pertemanan, _retweet_, dan lain-lain), tanpa perlu me-_refresh_ halaman.

=== Teknologi Pendukung Real-time Web

Real-time Web merupakan hal yang relatif kompleks. Terdapat beberapa teknologi yang bisa digunakan untuk mewujudkan real-time Web tersebut. Beberapa diantaranya merupakan standar (atau akan menjadi standar), sedangkan lainnya bukan merupakan standar.

==== _Ajax Technology_

Teknologi Ajax (kadang juga ditulis AJAX, singkatan dari _Asynchronous JavaScript and XML_ adalah sekumpulan teknologi yang pertama kali dicetuskan oleh Jesse James Garrett. Ajax memungkinkan browser untuk mengirim data dan mengambil data dari server secara _asynchronous_ (di latar belakang) tanpa mengganggu keseluruhan tampilan halaman Web. Kumpulan teknologi yang digunakan adalah:

* (X)HTML dan CSS untuk presentasi halaman Web
* DOM (_Document Object Model_) untuk menampilkan data secara dinamis
* XML dan XSLT untuk pertukaran data (seringkali tidak menggunakan
  XMLa tetapi JSON).
* Obyek XMLHttpRequest untuk komunikasi asynchronous
* JavaScript

==== Comet dan _Push Technology_

Comet merupakan istilah payung yang merangkum berbagai teknologi _push_, yaitu teknologi yang memungkinkan server untuk mengirimkan data ke browser tanpa diminta oleh browser.

===== SSE (_Server-Sent Events_)

SSE merupakan bagian dari spesifikasi standar HTML5 (bisa diakses di http://dev.w3.org/html5/eventsource/. Spesifikasi ini memungkinkan server untuk mem-_push_ data ke halaman Web menggunakan protokol HTTP. Meski masih dalam pengembangan, tetapi beberapa browser sudah mendukung (misalnya Google Chrome / Chromium) serta Safari. Beberapa peranti pengembangan di sisi server juga sudah mendukung spesifikasi ini. Pada Node.js, pemrogram bisa menggunakan paket sse, nsse, atau EventSource.

===== Bayeux Protocol

Protokol ini dikembangkan oleh _the Dojo Foundation_ yang mengembangkan software Dojo Toolkit. Protokol ini digunakan sebagai transport untuk pesan-pesan asynchronous melalui HTTP dengan latensi yang rendah antara klien dengan server. Pesan-pesan tersebut di-rute-kan melalui channel-channel yang diberi nama dan bisa dikirimkan ke:

* server ke klien
* klien ke server
* klien ke klien (melalui server)

Spesifikasi lengkap dari protokol ini bisa dilihat di http://svn.cometd.com/trunk/bayeux/bayeux.html.

===== BOSH Protocol

BOSH (Bidirectional-streams Over Synchronous HTTP) adalah protokol transport yang mengemulasi stream dua arah antara dua entitas (misalnya antara klien dengan server) dengan menggunakan banyak HTTP req/resp yang synchronous tanpa memerlukan polling yang sering atau respon yang terpotong-potong. Spesifikasi ini dikembangkan oleh komunitas serta yayasan XMPP dan bisa dilihat secara lengkap di http://xmpp.org/extensions/xep-0124.html

===== WebSocket

WebSocket merupakan teknologi Web yang menyediakan saluran komunikasi full duplex pada satu koneksi TCP. Protokol WebSocket distandarkan oleh IETF di RFC 6455 sedangkap API (_Application Programming Interface_) dikembangkan dan distandarkan oleh W3C sebagai bagian dari HTML5. Komunikasi antara klien dengan server dilaksanakan menggunakan TCP dengan nomor port 80.

WebSocket diimplementasikan di sisi server dan klien dan memungkinkan adanya interaksi yang lebih real-time daripada teknologi push karena protokol dan API ini diimplementasikan dan bisa digunakan di sisi klien maupun server. Browser yang sudah mendukung protokol dan API WebSocket ini adalah Chrome, Firefox, Safari, Opera, dan Internet Explorer.

Perkembangan dari WebSocket bisa dilihat dan diikuti di http://www.websocket.org/

=== Socket.io

==== Apa itu Socket.io?

_Socket.io_ adalah pustaka JavaScript yang merupakan implementasi dari protokol WebSocket serta berbagai improvisasi lain yang diperlukan untuk real-time web (_heartbeats, timeouts_, dan _disconnection_). Protokol transport yang didukung adalah sebagai berikut:

* WebSocket
* Adobe Flash Socket
* AJAX long polling
* AJAX multipart streaming
* Forever Iframe
* JSONP Polling

Pustaka ini terdiri atas pustaka untuk sisi klien (browser) dan server (menggunakan Node.js). Browser yang didukung adalah:

* Internet Explorer 5.5+ (desktop)
* Safari 3+ (desktop)
* Google Chrome 4+ (desktop)
* Firefox 3+ (desktop)
* Opera 10.61+ (desktop)
* iPhone Safari (mobile)
* iPad Safari (mobile)
* Android WebKit (mobile)
* WebOs WebKit (mobile)

==== Menggunakan Socket.io untuk Real-time Web

Socket.io melibatkan sisi klien dan sisi server. Pada sisi server, paket yang diperlukan adalah cocket.io, sementara untuk sisi klien (browser), diperlukan socket.io-client. Paket socket.io-client tidak diperlukan langsung pada sisi node_modules, tetapi ada beberapa file yang harus ditempatkan pada akses publik dengan maksud supaya bisa digunakan oleh browser.

===== Tentang Aplikasi

Aplikasi ini hanya merupakan contoh kecil dari real-time Web. Aplikasi terdiri atas sisi server dan klien/browser. Pada sisi server, aplikasi ini akan mengirimkan data ke browser (push). Sementara itu, browser akan menerima hasil push tersebut dan menampilkannya kemudian mengirimkan data ke server tanpa perlu melakukan proses _refresh_. Server hanya akan menampilkan data yang dikirimkan browser.

===== Membuat Kerangka Aplikasi dengan ExpressJS

Untuk membuat aplikasi ini, kita akan menggunakan ExpressJS dan
Socket.io. Listing lengkap dari contoh pada bab ini terdapat pada
*kode/bab-08/*

===== Instalasi Paket yang Diperlukan

File _package.json_ berisi beberapa informasi tentang aplikasi ini
serta beberapa paket yang diperlukan. Install paket-paket tersebut dengan menggunakan perintah _npm install_ di direktori tersebut.

===== Konfigurasi JavaScript untuk Browser

Browser juga memerlukan pustaka untuk Socket.io yang diperoleh dari
paket _socket.io-client_. Pada paket tersebut terdapat file
_socket.io.js_, salin file tersebut ke direktori _public/javascripts_.

===== Menjalankan Server Socket.io

Server socket.io menggunakan port 80 sehingga harus dijalankan oleh _root_. Keluaran pada sisi server tersebut merupakan keluaran yang sudah termasuk akses dari browser. Setelah server dijalankan, buka browser kemudian akses URL http://localhost. Setelah diakses melalui browser, server akan mengirimkan kode sumber HTML sebagai berikut:

[source,html,numbered]
----
<!DOCTYPE html>
<html>
    <head>
        <title>Contoh Socket.io + Express</title>
        <link rel="stylesheet" href="/stylesheets/style.css">
    </head>
    <body>
        <h1>Contoh Socket.io + Express</h1>
        <p>Contoh Socket.io + Express</p>
        <script src="/javascripts/socket.io.js"></script>
        <script>
            var socket = io.connect('http://localhost');
            socket.on('kirim ke browser', function (data) {
              document.getElementById("container").innerHTML=
                "<p>" + data.kalimatDariServer + "</p>";
            socket.emit('dari browser', { 
            kalimatDariBrowser: 'Kalimat ini dikirim dari browser' });
            });
        </script>
        <div id="container">
            <p>Contoh Socket.io + Express</p>
        </div>
    </body>
</html>
----
